name: "Release Manager: release RC when ready for review"

on:
  pull_request:
    types: [ready_for_review]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  get-pr:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_pr.outputs.pr_number }}
    steps:
      - uses: actions/checkout@v4
      # headが$GITHUB_REF_NAME, baseが$STABLE_BRANCHかつopenのPRを1つ取得
      - name: Get PRs
        run: |
          echo "pr_number=$(gh pr list --limit 1 --search "head:$GITHUB_REF_NAME base:$STABLE_BRANCH is:open" --json number  --jq '.[] | .number')" >> $GITHUB_OUTPUT
        id: get_pr
        env:
          STABLE_BRANCH: ${{ vars.STABLE_BRANCH }}

  echo:
    runs-on: ubuntu-latest
    needs: get-pr
    steps:
      - run: |
          echo "API_PR_NUMBER: $API_PR_NUMBER"
          echo "EVENT_PR_NUMBER: $EVENT_PR_NUMBER"
        env:
          API_PR_NUMBER: ${{ needs.get-pr.outputs.pr_number }}
          EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}

  release:
    uses: joinmisskey/release-actions/.github/workflows/create-prerelease.yml@main
    needs: get-pr
    if: ${{ github.event.pull_request.number == needs.get-pr.outputs.pr_number }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
      user: 'github-actions[bot]'
      package_jsons_to_rewrite: ${{ vars.PACKAGE_JSONS_TO_REWRITE }}
      use_external_app_to_release: ${{ vars.USE_RELEASE_APP == 'true' }}
      indent: ${{ vars.INDENT }}
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
